---
- name: Using varialbles in playbook #  this is the task name
  hosts: centos #  specifying host group where task needs to be run
  # vars:
  #   os_packages:
  #      - git
  #      - java-17-openjdk
  vars_files:
    - vars/packages.yaml
  tasks:
    - name: Install the package #  install packages:var/packages.yaml
      ansible.builtin.dnf: #  namespace/collection/module
        name: "{{ web_packages }}"
        state: present
    - name: Install httpd
      ansible.builtin.dnf:
        name: "{{  web_packages }}"
        state: present

- name: Add Multipe user
  hosts: centos

  tasks:
    - name: Ping the nodes
      ansible.builtin.ping:

    - name: Create new group
      ansible.builtin.group:
        name: dev
        state: present

    - name: Create user caaount
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        append: true
        groups: "{{ item.group }}"
      loop: "{{ list_of_users }}"
